typography_spectrum: 0.4878
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#9a1816'
    - '#616161'
    - '#8e8e8e'
  brandStrength: 0.5
  lightness: 0.09555361443199217
  saturation: 0.7777421346399933
  rhythmicContrast: 0.6871120075229555
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99617
analytics:
  google: null
  facebook: null
  twitter: null
name: Inside Psycho
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Inside Psycho Podcast
purpose: []
