name: Inside Psycho
favicon: null
layout_spectrum: 0.99617
typography_spectrum: 0.4878
title: Inside Psycho - a New Audio Series from A&E and CriticsChoice.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#9a1816'
    - '#616161'
    - '#8e8e8e'
  brandStrength: 0.005671022227033973
  lightness: 0.09555361443199217
  saturation: 0.7777421346399933
  rhythmicContrast: 0.6871120075229555
purpose: []
