layout_spectrum: 0.5176288583315909
typography_spectrum: 0.9974201638251543
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#9a1816'
    - '#616161'
    - '#8e8e8e'
  brandStrength: 0.5
  lightness: 0.09555361443199217
  saturation: 0.7777421346399933
  rhythmicContrast: 0.6871120075229555
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Mark Ramsey
  email: ''
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/068bcf69-b892-41ed-9a62-4cd35d609c19.png
name: Inside Psycho
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a4e0eebd-7d3e-4032-a497-797d9bf7ecfb.png
title: Inside Psycho Podcast
description: from Wondery and Mark Ramsey Media
purpose: []
