name: Inside Psycho
favicon: null
layout_spectrum: 0.255405945237726
typography_spectrum: 0.10006195190362632
title: Inside Psycho - a New Audio Series from A&E and CriticsChoice.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.005671022227033973
  lightness: 0.09555361443199217
  saturation: 0.7777421346399933
  rhythmicContrast: 0.6871120075229555
purpose: []
